### ISSUE TITLE
Various README clarifications

### ISSUE THREAD

**Issue by asmacdo** [cos-labs/scinet#44]
Step 4, ii - Make a note to include nano specific instructions including explanation of “^”

Step 5 - Add “Type exit to log out”

Step 8 - explain to use example url unless using a forked version
          - alter example url to harryrybacki from hrybacki

Step 9,  ii - to edit this file requires root
    iii - once running, use ctr c to kill

Step 10 - change to /vol dir before checking out citelet

**Comment by HarryRybacki-zz** [comment]
Closed in [b2b327da12](https://github.com/CenterForOpenScience/scinet/commit/b2b327da122e263c4826ac2a387d82872a0fd20f)
