### ISSUE TITLE
Review Kango framework's ability to add user specific configuration page

### ISSUE THREAD

**Issue by HarryRybacki-zz** [cos-labs/scinet#53]
This is where users will either select a group to associate with OR be pointed to a page directing them HOW to create a new group.

**Comment by HarryRybacki-zz** [comment]
Ping @asmacdo post your findings, good sir!

**Comment by asmacdo** [comment]
![optionspage](https://f.cloud.github.com/assets/1028657/2431745/ad1a9830-ad41-11e3-85a4-c2959d80be97.jpg)

The page dynamically generates the drop down list from a JSON get. Data is stored via Kango storage. I can include a form or a link to submit a new group.

**Comment by HarryRybacki-zz** [comment]
Because the Kango-based extensions simply load the bookmarklet script for Citelet and execute there is no simple way to modify the payloads and include affiliation information. As a result, we have opted  modify the Chrome Extension for the time being. The FireFox extension will work but users won't be able to affiliate their submissions with any of the organizations.
