### ISSUE TITLE
Design API framework 

### ISSUE THREAD

**Issue by HarryRybacki-zz** [cos-labs/scinet#6]
Two endpoints:

1) /raw -- handles raw or unparsed data
2) /articles -- handles parsed data in Scholarly standard JSON format

**Comment by HarryRybacki-zz** [comment]
Completed. 

Alpha version of API is now in the repo.

**Comment by lyndsysimon** [comment]
Is an article an object that ultimately results from information submitted through `/raw`?

If so, perhaps consider that `/raw` should be a sibling to `/parsed`, and `/articles` could be `/parsed/articles`.

**Comment by HarryRybacki-zz** [comment]
Yes, eventually. But, that's a long way off. We have multiple ways for users to drop off files via the raw endpoint. Some are simple to parse and others are... not so easy. 

I had originally opted for a single database containing multiple collections i.e. parsed and unparsed. But, the command decision was to maintain one clean and consistent database independent of its dirtier cousin for now.
